name: churn-prediction
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.10
  - pip
  - pip:
      - pandas==2.2.2
      - numpy==1.26.4
      - matplotlib==3.8.4
      - seaborn==0.13.2
      - scikit-learn==1.4.2
      - xgboost==2.0.3
      - lightgbm==4.3.0
      - lifelines==0.27.8
      - tensorflow==2.15.0
      - keras==2.15.0
      - scipy==1.13.0
      - joblib==1.4.2
      - tqdm==4.66.4
      - shap==0.44.1
      - ipykernel==6.29.4
      - jupyter==1.0.0
